In [1]:
#coding: utf8
from src.utils import HashCodeProblem
import numpy as np
import operator

In [2]:
def heuristeasy(Mscores, ph):
    
    '''
    Mscores : la matrice de scores
    ph : l'indice de la photo de laquelle on part
    '''
    
    nb_photos = Mscores.shape[0]
    list_ph = [i for i in range(nb_photos)]
    
    nb_regardees = 0

    out_couplage = [ph]
    final_score = 0

    while nb_regardees < nb_photos:
    
        list_ph.remove(ph)
    
        if len(list_ph) == 0: break
    
        scores_ph = {}
    
        for other_ph in list_ph:
            scores_ph[other_ph] = Mscores[ph][other_ph]
            score_ph = max(list(scores_ph.values()))
    
        kept_ph = max(scores_ph.items(), key=operator.itemgetter(1))[0]
        out_couplage.append(kept_ph)
        final_score += score_ph
    
        ph = kept_ph
        nb_regardees += 1
        
    return final_score, out_couplage

In [7]:
b = np.random.random_integers(0,10,size=(8,8))
scores_matrix = (b + b.T)
init_ph = 0 # indice de la première photo regardée

hash_score, slide_show = heuristeasy(scores_matrix, init_ph)

print('Test Scores Matrix :\n', scores_matrix)
print('\n')
print('Scores :', hash_score)
print('Slide Show :', slide_show)

Test Scores Matrix :
 [[12 11  1 10 15  5  8 14]
 [11 18 10  8 13 17 10 11]
 [ 1 10 16 18  6 12 10 18]
 [10  8 18  8 10 18 15 15]
 [15 13  6 10  4  9  9 16]
 [ 5 17 12 18  9 10 13  2]
 [ 8 10 10 15  9 13 12  6]
 [14 11 18 15 16  2  6  2]]


Scores : 112
Slide Show : [0, 4, 7, 2, 3, 5, 1, 6]


/Users/galinette/Desktop/kpc-hash/hashcode/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """Entry point for launching an IPython kernel.
